# Generated by Django 4.0.3 on 2022-08-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pass_reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailinfo', models.CharField(max_length=100)),
                ('passreset_info', models.IntegerField()),
            ],
            options={
                'db_table': 'for_passreset_info',
            },
        ),
    ]
